### ISSUE TITLE
BuddyPress breaks disabling notification for new users

### ISSUE THREAD

**Issue by Zodiac1978** [johnbillion/wp_mail#1]
I've written a blog post about the problem (in German) here:
https://torstenlandsiedel.de/2018/09/13/benachrichtigungsmails-fuer-admins-abstellen/

Please see these tickets for more details:
https://core.trac.wordpress.org/ticket/36009#comment:14
https://buddypress.trac.wordpress.org/ticket/7597#comment:7

**Summary:**
Sine WordPress 4.6 `wp_send_new_user_notifications` has a new parameter which sets up who should get the notification. Default is `both` (user and admin). You can remove this function via `remove_action` and re-add a new function which has the default changed to `user` instead to disable the admin notification.

The problem is that BuddyPress didn't know this and makes its own thing in `bp-members-functions.php`:
```
if ( apply_filters( 'bp_core_send_user_registration_admin_notification', true ) ) {
    wp_new_user_notification( $user_id );
}
```

It did not use the third parameter and adds a different way to disable the notification via filter.

So you need an additional filter to disable it:
```
add_filter( 'bp_core_send_user_registration_admin_notification', '__return_false' );
```

**Comment by johnbillion** [comment]
Thanks for the report, but this isn't really related to the core emails that WordPress sends. I'm not interested in maintaining a list of the emails that BuddyPress or bbPress send but I'm happy to link to such a list if someone wants to maintain it.

**Comment by Zodiac1978** [comment]
> but this isn't really related to the core emails that WordPress sends

I thought this is related to https://github.com/johnbillion/wp_mail#a-new-user-is-created as BuddyPress is using the WP core function.

**Comment by johnbillion** [comment]
Hey man no need to be like that. I was just pointing out that the issue you reported is related to the BuddyPress plugin and this list would be unmaintainable if I started listing every bug with every plugin. No bad feelings.

A separate list that documents the emails sent by BuddyPress is a good idea, but as I said above I'm not interested in maintaining it because I don't use BuddyPress.

**Comment by renatonascalves** [comment]
Folks! BuddyPress core committer here! 

I confirmed internally the bug and will tackle that on BuddyPress.

@johnbillion I agree! I have been thinking about compiling this BuddyPress email list for quite some time. Probably will in the near future. :)

**Comment by Zodiac1978** [comment]
> this list would be unmaintainable if I started listing every bug with every plugin

Agreed @johnbillion. I thought bbPress/BuddyPress are seen as core projects and therefore maybe are worth to mention here. Additionally I don't suggested to maintain a complete list, but to mention this problem in the "How to disable" area of your list.

But this is your list and your decisions and I apologize for my last sentence. It was unrelated to this issue and should have been not posted. I was angry about a private law problem (lost in court although I am 100% right, because the other party lied and the judges don't cared).

**Comment by Zodiac1978** [comment]
Hi @renatonascalves!

Thanks for tackling this issue. If you already have opened a trac ticket for it, it would be great if you could post it here. Otherwise I can open a new ticket myself if this would help you. 

Thanks in advance!

**Comment by renatonascalves** [comment]
@Zodiac1978 If you could open a ticket, that would be great! Thank you! :)

**Comment by Zodiac1978** [comment]
@renatonascalves Here it is: https://buddypress.trac.wordpress.org/ticket/8081#ticket

**Comment by renatonascalves** [comment]
Thank you! =)
