### ISSUE TITLE
wp_fatal_error_handler_enabled is not applicable for third party plugin

### ISSUE THREAD

**Issue by mzaheerdad** [johnbillion/wp_mail#12]
Hi,
First of all thanks for the wonderful information. The filter you specified in section "A fatal error occurs" for disabling fetal error email is not working. Because it call when third party plugin are not yet loaded so how one can filter it.

**Comment by johnbillion** [comment]
Yeah you're completely correct, this filter is run before plugins are loaded. It can be filtered by constructing a `$wp_filter` object in your wp-config.php file though. I'll find out the details and add a note about this.

**Comment by johnbillion** [comment]
I updated the docs in WordPress core for this: https://core.trac.wordpress.org/changeset/49489

Need to copy them to this repo.
